# Source: cluster-api-aws/templates/aws-machinetemplates-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: cb7ada4e-537a-4821-a7d1-75bbf442c2c9-control-plane
  namespace: cb7ada4e-537a-4821-a7d1-75bbf442c2c9
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: tks-seoul
      rootVolume:
        size: 20
        type: gp2
